### ISSUE TITLE
Pubmed  API GET Method

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2023group9#115]
### Issue Description

I will implement get method for Pubmed Rest API

### Steps

- [x] Code Implemented
- [ ] Tests created and passed 
- [ ] PR reviewed and merged
- [ ] Documentation added

**Comment by oguzpancuk** [comment]
**Pubmed GET Method:**

import requests

def get_pubmed_data(query):
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
    endpoint = "esearch.fcgi"
    params = {
        "db": "pubmed",
        "term": query,
        "retmax": 10
    }
    response = requests.get(base_url + endpoint, params=params)
    if response.status_code == 200:
        return response.text
    else:
        return None

**Pubchem GET Method:**

import requests

def get_pubchem_data(compound_name):
    base_url = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/"
    endpoint = "/JSON"
    params = {
        "property": "IUPACName,MolecularWeight,IsomericSMILES",
        "record_type": "3d",
        "output_type": "JSON"
    }
    response = requests.get(base_url + compound_name + endpoint, params=params)
    if response.status_code == 200:
        return response.json()
    else:
        return None

**Comment by hakanaktas0** [comment]
The PR of this issue has been merged.

**Comment by uyduranomer** [comment]
This issue has been cancelled.
