### ISSUE TITLE
Requirements should be documented

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#12]
Basic requirements should be documented for the project.

**Comment by Bera0422** [comment]
Basic requirements are grouped and added to [Requirements](https://github.com/bounswe/bounswe2023group9/wiki/Requirements) page.

**Comment by hakanaktas0** [comment]
Requirements may be revised in the future, but they are completed for now. They have been added to [wiki](https://github.com/bounswe/bounswe2023group9/wiki/Requirements)
