### ISSUE TITLE
Similar Projects should be studied

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#13]
Projects similar to ours should be found and examined. We should also contact stakeholders if we can.

**Comment by hakanaktas0** [comment]
There aren't many projects like what we are trying to achieve. [this](https://www.connectedpapers.com/) project is the most similar one(also the only one) I could find.

**Comment by hakanaktas0** [comment]
Wiki page for Similar projects is created and added to the sidebar.
Research on [Connected Papers](https://www.connectedpapers.com/) is added to the page.

**Comment by laylaylo** [comment]
I've come across [CiteSpace](https://citespace.podia.com/exemplars), a project that shares some similarities with ours. I will add my research findings to the related wiki page by the end of the day.

**Comment by laylaylo** [comment]
Even though there are few other similar projects to ours, such as SciGraph, none of them are significantly different from the ones we have examined. Therefore, as there is nothing essential left to add regarding this issue, and its requirements have been fulfilled, I am closing it.
