### ISSUE TITLE
Meeting #3 Notes should be added

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#17]
* Notes taken in meeting at 15/03/2023 should be added according to Meeting Notes Template
* A related Wiki page should be created and put in appropriate position in Wiki sidebar

**Comment by uyduranomer** [comment]
meeting 3 was documented in [CmpE352 Meeting #3](https://github.com/bounswe/bounswe2023group9/wiki/CmpE352-Meeting-%233) page
