### ISSUE TITLE
Dockerization and deployment of practice app

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#175]
### Issue Description

The dockerization and the deployment of the practice app with the docker image to an AWS instance will be done.

### Steps

- [x] Dockerization
- [x] Deployment
- [x] Testing

### Deadline for the Issue

12.5.2023

**Comment by hakanaktas0** [comment]
App has been dockerized and pushed to the hub which can be accessed from repo hakanaktas0/practice-app. App is also deployed in an AWS instance which can be accessed http://35.171.9.117:8000/ here
