### ISSUE TITLE
creation and documentation of high-level mock-ups 

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#18]
### Issue Description

the documentation of detailed, comprehensive, and realistic high-level mock-up scenarios to how the requirements could satisfy the project owner. 

**Mock-up Scenarios**
- [x] Scenario creation for non-logged in user and non-contributor 
- [x] Scenario creation for contributor
- [x] Scenario creation for reviewer

**Mock-up Web pages**
- [x] Log in page
- [x] Sign up page
- [x] Home/explore page for non logged in user
- [x] Home/explore page for logged in user
- [x] Home/explore page with keyword search
- [x] #21
- [x] #19
- [x] #22
- [x] #23

### Deadline for the Issue

20.03.2023 - Monday

**Comment by hakanaktas0** [comment]
First version of the mock-ups have been completed and added to wiki.
