### ISSUE TITLE
Documentation of APIs

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#185]
### Issue Description

The utilized and implemented APIs should be documented

### Steps

- [x] #186
- [x] #187
- [x] #190 
- [x] #191 
- [x] #197 
- [x] #198 
- [x] #204 
- [x] #205 
- [x] #211 
- [x] #212 
- [x] #217 
- [x] #218 
- [x] #220
- [x] #221
- [x] #222
- [x] #223
- [x] #232
- [x] #233
- [x] #234
### Deadline for the Issue

12.5.2023

**Comment by Bera0422** [comment]
Documentations of the GET method for ERIC API and the POST method for saving paper lists are prepared.

**Comment by mehmetSuzer** [comment]
All documentations are done
