### ISSUE TITLE
Subsection of team members in the milestone 2 report

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#192]
### Issue Description

A section summarizing member contributions. A subsection will be created for each team member that summarizes their contributions (each team member must write their own section). The subsections should be organized in alphabetical order by surnames of members. Each member section will provide:

- Their own name (as section name)
- Links to important issues (git issues) and wiki documentation related to practice application
- The name, route, description of utilized third party URIs
- The name, route, description of the created API functions
- Description of unit tests. You can include code fragments to illustrate.
- Sample calls: Show a transcript of a request and response for the API functions you used and that you provide. The transcript should include the request and the detailed response (headers, status code, json etc.)
- Any other significant work related to this release (such as Docker, AWS, DB, Framework)
- Describe any challenges you met during implementation.

### Steps

- [x] #194
- [x] #193
- [x] #195
- [x] #196
- [x] #206 
- [x] #216
- [x] #219 
- [x] #226 
- [x] #236 
### Deadline for the Issue

12.5.2023

**Comment by hakanaktas0** [comment]
All members completed their individual contribution reports.
