### ISSUE TITLE
Scenarios and Mock-up | Criteria

### ISSUE THREAD

**Issue by mehmetSuzer** [bounswe/bounswe2023group9#20]
### Issue Description

Criteria parts of the scenarios should be filled with the corresponding requirements 

### Steps

- [x] Requirements should be examined
- [x]  Whether or not scenarios satisfy the requirements should be checked
- [x] Necessary parts of the wiki pages should be edited

### Deadline for the Issue

20.03.2023 Monday 13.00

**Comment by ArslanArdavic** [comment]
I added the criteria for Mock-ups. You @mehmetSuzer  may close this issue after checking the wiki pages.

**Comment by mehmetSuzer** [comment]
I added some extra requirements at the end of the criteria sections. I believed that they are related to the scenarios. I will close the issue after you @ArslanArdavic check them.

**Comment by ArslanArdavic** [comment]
Great! I guess we are done here.
