### ISSUE TITLE
Workspace page for contributor user (should have add node request)

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#21]
Workspace for contributors should include:

- [x]  Main Workspace page where contributors create workspaces and entries to keep track of the progress
- [x]  A way to reach out to possible collaborators
- [x]  A way to send to review
- [x]  A way to resolve issues and proposed edges

**Comment by laylaylo** [comment]
As I reviewed the reviewer page on our sketching tool folder, it seemed pretty clear overall, however I have one question related to **current edges** part. Is the reason not splitting it into **predecessor and successor nodes** not having any child nodes of **not ready** node? Additionally, should we assume  that the workspace will be disappeared after adding this node?

I realize that this question may not be directly related to the workspace page. I might have missed this detail  in our previous discussions.

**Comment by hakanaktas0** [comment]
All the nodes listed below current edges are predecessor nodes. I remember having a discussion about adding a node between nodes, but as far as I remember we didn't discuss it in detail so I chose not to include it.

This issue should be discussed again in the next meeting.

**Comment by hakanaktas0** [comment]
The issue of predecessor/successor nodes has been resolved in the meeting with the product owner.
