### ISSUE TITLE
Reviewer page with review request

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#22]
This page should include;

- [x] Notification to notify the reviewer to review
- [x] Review process 
- [x] Approval and Publishing

**Comment by laylaylo** [comment]
As I reviewed the reviewer page on our sketching tool folder, it **shows clearly** our use cases created in the scenario and aligns with our project requirements. Also, I believe that **keeping design simple** ,as you did, at this stage preferable to adding advanced UI elements. Good job!
