### ISSUE TITLE
Collaborator workspace page

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#23]
This page should demonstrate;

- [x] Collaboration request
- [x]  Workspace Ownership

**Comment by laylaylo** [comment]
As I reviewed the reviewer page on our sketching tool folder, it **shows clearly** our use cases created in the scenario and aligns with our project requirements. Also, I believe that **keeping design simple**, as you did, at this stage preferable to adding advanced UI elements. Good job!
