### ISSUE TITLE
Onboarding and Who are we editing

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#237]
### Issue Description

Need to onboard the project reading wiki pages.
Need to add my info, github profile to readme and who are we page.

### Steps

- [x] Read wiki page
- [x] Inspect diagrams
- [x] Add yourself to Read.me and who are we files

### Deadline for the Issue

09.10.2023

**Comment by hakanaktas0** [comment]
Little note for next time, 
- add the subtasks of the issue as steps
- assign yourself to the issue
- put labels
