### ISSUE TITLE
A project plan wiki page will be published

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#244]
Prepared project plan will be published in the wiki as a page or will be submitted as a file.

**Comment by hakanaktas0** [comment]
The project plan has been prepared and uploaded to a [page](https://github.com/bounswe/bounswe2023group9/wiki/Project-Plan) in wiki.

**Comment by Bera0422** [comment]
Maybe the missing part of the line 19 can be fixed but it may not be a big problem. Beyond that, I think the plan is nice enough to get started with the implementation. Nice job!

**Comment by uyduranomer** [comment]
The duration of the 2nd week looks as 8 days. This can be fixed on the next update I think. Everything else is nice, and this is good enough to continue 👍 I am closing the issue.

Ellerine sağlık...
