### ISSUE TITLE
A Responsibility Assignment Matrix (RAM) will be prepared

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#246]
### Issue Description

A Responsibility Assignment Matrix (RAM) will be prepared and published in the wiki.

### Steps

- [x] #238 
- [x] The preparation
- [x] #247

### Deadline for the Issue

10.10.2023 - Tuesday - Lab Hour

**Comment by hakanaktas0** [comment]
Responsibility Assignment Matrix is ready and published.
