### ISSUE TITLE
A Responsibility Assignment Matrix (RAM) wiki page will be published

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#247]
Prepared responsibility assignment matrix will be published in the wiki as a page or will be submitted as a file.

**Comment by hakanaktas0** [comment]
Using the task list we created in issue #238  I have created the RAM in Google Sheets and put the [link](https://docs.google.com/spreadsheets/d/1BwoXg0kADAVohLa8nYNR2tXjQg6OQYqQ/edit?usp=sharing&ouid=100219605893056724079&rtpof=true&sd=true) to it to the [wiki page](https://github.com/bounswe/bounswe2023group9/wiki#responsibility-assignment-matrix-ram)

**Comment by omerfaunal** [comment]
That seems fair and nice. Issue can be closed.
