### ISSUE TITLE
Backend technologies will be decided

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#248]
### Issue Description

Backend, database, and cloud technologies will be reserched and decided for the project.

### Steps

- [x] Research of proposed and probable technologies and their cons & pros
- [x] Discussion and deciding

### Deadline for the Issue

10.10.2023 - Tuesday - 17.00

**Comment by omerfaunal** [comment]
As a final decision, we decided to use followings:

Backend: Django
Database: Postgresql (stored in Supabase) 
Cloud: AWS, Supabase
