### ISSUE TITLE
Review of the Project Plan

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#252]
### Issue Description

Since milestones will be announced after the project plan creation, we need to ensure that the project plan aligns with milestones

### Deadline for the Issue

12.10.2023- Thursday - 23.59

**Comment by Zulalm** [comment]
I reviewed the project plan and I couldn't find any information about the implementation of requests, notifications, tags and wiki-tags. Are they covered by the other tasks? If so, which tasks include them? It might be useful to state them clearly in the plan.

**Comment by hakanaktas0** [comment]
@Zulalm you are right. I updated the project plan to include all class implementations for the back-end team.

**Comment by uyduranomer** [comment]
Everything looks correct and as we discussed after the addition of the model classes. This task is completed I think.
