### ISSUE TITLE
Weekly Progress Report #2

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#253]
### Issue Description

The Weekly Progress Report for the lab meeting on 10.10.2023 should be prepared.

### Deadline for the Issue

10.10.2023 - Tuesday - 22.00

**Comment by laylaylo** [comment]
Most of it is written during lab hours and now, it's sent to Discord channel to do last revision.

**Comment by uyduranomer** [comment]
the progress report added in [ its wiki page](https://github.com/bounswe/bounswe2023group9/wiki/Weekly-Progress-Report-%232-%7C-10.10.2023) and added in the reports folder in the root directory. It ahs been reviewed in the linked pull request and merged into the main branch. I am closing this issue.
