### ISSUE TITLE
Use Case Diagram will be implemented...

### ISSUE THREAD

**Issue by ArslanArdavic** [bounswe/bounswe2023group9#26]
### Issue Description

Use Case diagram specified according to requirements will be drawn according to users:

### Steps

- [x] #27
- [x] #28
- [x] #30
- [x] #29
- [x] #31
- [x]  #85

### Deadline for the Issue

03.04.2023

**Comment by uyduranomer** [comment]
All diagrams have been completed but they have to be combined.

**Comment by uyduranomer** [comment]
All of the sub-issues were reviewed and this issue is ready to be merged.
