### ISSUE TITLE
Updating the requirements

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#260]
### Issue Description

Updating the requirements according to the decisions taken and discussions with the product owner	

### Deadline for the Issue

13.10.2023

**Comment by Zulalm** [comment]
I updated "node" as "workspace" on the requirement 1.1.1.4.1. I added 1.1.1.5.5 and 1.1.1.5.6 requirements which are related with the abilities of admins.

**Comment by Zulalm** [comment]
As I reviewed the requirements I found that tags and wiki tags are not clearly defined. We may define these terms in the glossary as follows:

**Tag** : An object that identifies and categorizes specific objects such as nodes and users.
**Wiki Tag**: An object that is used to store information related to a term or concept found in Wikipedia.

In addition, we can write a new requirement to specify that which users should be able to add tags and wiki tags. Here is my suggestion:
1.1.1.3.10 Contributors shall be able to add tags and wiki tags to their workspaces.

**Comment by uyduranomer** [comment]
I have updated the requirements page according to the decisions made in the last lab and the results of the discussions between the product owners. I have made a lot of updates and all of them can be seen in the [page history](https://github.com/bounswe/bounswe2023group9/wiki/Requirements/_history) with their explanations. I have fixed some ambiguities also. The final version of the requirements can be seen in the [requirements page](https://github.com/bounswe/bounswe2023group9/wiki/Requirements).

**Comment by uyduranomer** [comment]
This issue was waiting for the approval of the product owner. I think for this week's task, we completed everything needed for this issue already. I am closing this issue and we can open a new issue that covers the feedback of the product owner next week.
