### ISSUE TITLE
Updating the UML diagrams according to the updates in the requirements	

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#261]
### Issue Description

Updating the UML diagrams according to the updates in the requirements
--

<br class="Apple-interchange-newline">

### Steps

- [x] Updating Sequence Diagrams
- [x] Updating Class Diagrams
- [x] Updating Use Case Diagrams

### Deadline for the Issue

15.10.23

**Comment by hakanaktas0** [comment]
In the class diagram, the admin class inherits from the reviewer class. This contradicts the requirements.

**Comment by Brunettow** [comment]
I updated sequence diagrams according to the revisions on issue [#251](https://github.com/bounswe/bounswe2023group9/issues/251).

**Comment by Zulalm** [comment]
> In the class diagram, the admin class inherits from the reviewer class. This contradicts the requirements.

I updated the class diagram and fixed this issue.

**Comment by uyduranomer** [comment]
I updated the requirements according to the discussions within the team and the product owners. Please re-check the UML diagrams accordingly. If you see any problem in the new version, please leave a comment under the issue #260 .

**Comment by laylaylo** [comment]
Requirements are revised again based on feedbacks from PO feedbacks on Discord channel by @Zulalm and I reviewed them. I check [Use Case Diagrams](https://github.com/bounswe/bounswe2023group9/wiki/Use-Case-Diagram) and did some small changes accordingly to updated requirements.
