### ISSUE TITLE
Review of the RAM table	

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#262]
### Issue Description

Review of the RAM table
--
Responsibility Assignment Matrix should be updated.

<br class="Apple-interchange-newline">

### Steps

- [x] Teams are redistributed
- [x] Class implementations are added as tasks
- [x] Updated RAM is published

**Comment by hakanaktas0** [comment]
The RAM has been updated and the links in the wiki are also updated.
new [link](https://docs.google.com/spreadsheets/d/1KRzeKsct_cMXewCietioMtawmq9x1PCp/edit?usp=sharing&ouid=100219605893056724079&rtpof=true&sd=true)

**Comment by uyduranomer** [comment]
I reviewed the new RAM table and everything looks as we discussed and planned in the lab meeting. Everything looks correct and I think this task is already completed.
