### ISSUE TITLE
Signup Page	

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#266]
### Issue Description

Signup Page
--

<br class="Apple-interchange-newline">

### Steps

- [x] App Routing between Login Page and Sign Up Page
- [x] Usage of App Text Fields and App Button 
- [x] Strong Password Checker
- [x] Design of the Sign Up Page

### Deadline for the Issue

17.10.2023 17.00

**Comment by Brunettow** [comment]
Navigation is implemented. Also text overflowing errors are handled.

**Comment by mehmetSuzer** [comment]
A strong password checker has been implemented and added to sign up page.

**Comment by omerfaunal** [comment]
Controlled and merged to main
