### ISSUE TITLE
Login Page	

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#267]
### Issue Description

Login Page
--

<br class="Apple-interchange-newline">

### Steps

- [x] Implementation of App Button
- [x] Implementation of App Text Field
- [x] Login Page Design

### Deadline for the Issue

17.10.2023 17.00

**Comment by mehmetSuzer** [comment]
The text field and the button for the application is implemented.
I completed the design of the Login Page.
