### ISSUE TITLE
New Labels should be created

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#272]
### Issue Description

We need new labels. I suggest we add front-end and back-end. If you have any suggestions please comment.

### Steps

- [x] front-end
- [x] back-end

### Deadline for the Issue

15.10.2023

**Comment by hakanaktas0** [comment]
I think we should get rid of the status labels and use the status feature of Github Projects instead.

**Comment by hakanaktas0** [comment]
I think we can also remove the size and priority labels to use Github Projects insted.

**Comment by uyduranomer** [comment]
I agree with you about the features of the github projects. I think we may use labels difficulty, type, and work categorizations for the rest of the projects lifecycle. On the other hand, I think this removal of unnecessary labels will make label choice more easy, simple and faster.

**Comment by hakanaktas0** [comment]
Status labels have been removed.
