### ISSUE TITLE
Transfer Project Plan to Github Project Road Map Page

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#283]
### Issue Description

Project Plan should be transferred to Road Map Page.

**Comment by hakanaktas0** [comment]
I have transferred almost all the planned tasks to the Roadmap.

**Comment by laylaylo** [comment]
I reviewed Roadmap and it aligns well with [Project Plan on Wiki](https://github.com/bounswe/bounswe2023group9/wiki/Project-Plan). As noted in the progress report feedback, it's great to see you've added milestones.
