### ISSUE TITLE
Bug: Backend should return different error messages

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#287]
### Issue Description

For different cases backend should return different login and signup errors.

Like: This email is not valid vs. 

### Steps

- [x] Change authentication API...
- [x] Warn frontend...
- [x] Deploy those changes...

### Deadline for the Issue

31.10.2023

**Comment by hakanaktas0** [comment]
I believe this issue is resolved @omerfaunal  ?

**Comment by omerfaunal** [comment]
This is resolved
