### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#288]
### Issue Description

Design and implementation of profile page.

### Steps

- [x] Page Design
- [x] Provider Implementation
- [x] Account Settings Implementation
- [x] About Me Section Implementation
- [x] Bringing Parts Together
- [x] Navigation to Other Screens

### Deadline for the Issue

22.10.2023 - Sunday - 23.59

**Comment by Zulalm** [comment]
We discussed and decided on the design of the profile screen with @Brunettow and @leylo.  I implemented the About Me section and wrote a structure for profile page. I used the code from home-page branch for profile page implementation. I pushed the code to the profile-page branch. However, implementation is incomplete now. When a provider that gets user data from the backend is implemented, I will update the code.

**Comment by Brunettow** [comment]
Settings part is designed.
Previous Design was not coherent with app theme so I changed according to discussions.
There can be minor changes on web design, especially on app bar since we discussed that to have a general app bar for website.
### Current Design:
![DeepinScreenshot_google-chrome_20231023134505](https://github.com/bounswe/bounswe2023group9/assets/63921045/1ac3310d-9367-4f3b-962b-bafec2c08b67)

**Comment by Zulalm** [comment]
I implemented a provider to retrieve data for profile page . Related code can be found on profile_page branch.

**Comment by laylaylo** [comment]
Initial profile page design and basic functionality like profile page with about me section and profile setting section are done, however some design we planned like showing **activity of user** and **testing** couldn't be implemented due to the dependency on the API calls that are not implemented yet. New issues related to them are opened. #332 #322

**Comment by Zulalm** [comment]
I think this issue was completed last week but it was forgotten to be closed. Since the status of profile page can be followed on #332, I am closing this issue.
