### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#289]
### Issue Description

Design and Implementation of the Home Page

### Steps

- [x] Search Bar
- [ ] Recent Nodes Section
- [x] Navigation to Other Pages

### Deadline for the Issue

24.10.2023 - Tuesday - 17.00

**Comment by mehmetSuzer** [comment]
I created a branch named "home-page" and implemented a basic structure of the home page.
If the design is OK for you, we can go on with this implementation.

**Comment by omerfaunal** [comment]
Reviewed the codes and added some comments.

For the routing part, let's do some research about GoRouter and redirection.
