### ISSUE TITLE
Basic User

### ISSUE THREAD

**Issue by ArslanArdavic** [bounswe/bounswe2023group9#29]

**Comment by Bera0422** [comment]
The Basic User Use Case Diagram can be viewed on LucidChart. It needs review to be considered as finished.

**Comment by ArslanArdavic** [comment]
Hi there! @Bera0422 @laylaylo  I have examined Use Case diagram for Basic User. It was very well organized, great job! However, because Basic User is already registered, I think Sign-up should be an action of Guest User. If you also agree we should inform  @defabdullah  about this.

**Comment by laylaylo** [comment]
Good catch! I totally agree, we somehow missed it. Additionally, Log-in seems the same case. It should be an action of Guest User since Basic User is already logged in. I moved related sub-chart into Guest User page on Lucidchart and also pinged @defabdullah.

**Comment by Bera0422** [comment]
Well, I think Log-in is okay for _**Basic Users**_ since they will need to log in to use the platform functionalities. Also _**Guests**_ cannot log in since they are not signed up users.

**Comment by laylaylo** [comment]
Okay, I see your point @Bera0422 . I thought like **Guests** could try to log-in and if their credentials get verified, they will become **Basic User**. I guess where to put Log-in activity depends on how you think and it can be either way, so it's kind of design choice. Let's keep it in Basic User as you suggest.

**Comment by hakanaktas0** [comment]
This part of the use case diagram is reviewed and ready to be merged.
