### ISSUE TITLE
Generic Parent Page

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#290]
### Issue Description
Create a generic parent page with Sliver App Bar options
-- 

### Steps

- [x] Create sliver app bar
- [x] Create generic page with app bar and body

### Deadline for the Issue

22.10.2023 - Sunday - 23.59

**Comment by omerfaunal** [comment]
Created a generic page, now will write some documentation for easier use for project members.

**Comment by omerfaunal** [comment]
Merged to the main
