### ISSUE TITLE
Admin Class/Model Implementation

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#291]
### Issue Description

Admin user type will be implemented.

### Steps

- [x] Admin class will be created inside models.py, on Django app.
- [x] Migration will be made in order to create database model.
- [x] Afterwards unit tests will be implemented  and run.

### Deadline for the Issue

22.10.2023 - Sunday - 23.59

**Comment by hakanaktas0** [comment]
All done. PR is merged.
