### ISSUE TITLE
Node Class/Model Implementation

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#294]
### Issue Description

Node Class/Model should be implemented according to [the Class Diagram](https://github.com/bounswe/bounswe2023group9/wiki/Class-Diagram).
### Steps

- [x] Implementing the attributes
- [x] Implementing the related functions
- [x] Writing and running unit tests

### Deadline for the Issue

21.10.2023 - Saturday - 23.59

**Comment by Bera0422** [comment]
The basic fields and functionalities are implemented and merged in PR #302.
