### ISSUE TITLE
GoRouter Implementation

### ISSUE THREAD

**Issue by defabdullah** [bounswe/bounswe2023group9#308]
### Issue Description

In frontend, we currently navigate between different screens by passing parameters and managing page transitions manually. To improve code maintainability and navigation within our app, we want to implement routing using GoRouter package.

### Steps

- [x] Research and learn GoRouter
- [x] Decide URL format for pages (i.e profile/user-id or profile/username etc.)
- [x] Integrate GoRouter into our Flutter app
- [x] Replace all current manual navigation with GoRouter's routing capabilities

### Deadline for the Issue

14.11.2023 - Tuesday - 17.00

**Comment by omerfaunal** [comment]
@laylaylo designed initial structure, go router page setups and changed current navigations.
@omerfaunal changed url strategy, added redirect (If user logged in redirect if tries to open login page), fixed bugs, added routing strategy to app bar.

**Comment by laylaylo** [comment]
PR merged and all navigation, even this week's work, uses GoRouter. This task is done.
