### ISSUE TITLE
Revision of the High Level Mock-ups

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#32]
### Issue Description

Product owner has pointed out some issues in the mock-ups we provided. They should be revised according to their wishes.

### Steps

- [x] Current edges statement should be changed
- [x] The topic chosen for the mock-up should be changed
- [x] Collaborating Contributor page is missing in the wiki
- [x] Reviewer should only review the final entry
- [x] Reviewer shouldn't create issues/tasks, just comments
- [x] The ability to add theorem nodes
- [x]  Some one else can add a proof to a theorem posted by someone

### Deadline for the Issue

02.04.2023 Sunday - 23.59

**Comment by Zulalm** [comment]
I reviewed the new mock-ups and they look consistent with the feedbacks given by the product owner.
