### ISSUE TITLE
Preparation for Deployment and Revision for Customer Milestone 1

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#325]
### Pre-release Related Sub-issues
- [x] #339 
- [x] #368 

### Other deliverables Related Sub-issues
- [x] #374 

### Deadline for the Issue
Pre-release of the software (31.10.2023, 22:00), Other deliverables (03.11.2023, 17:00).

**Comment by uyduranomer** [comment]
All subtasks are done, I am closing this issue
