### ISSUE TITLE
Proof Model GET API Implementation

### ISSUE THREAD

**Issue by ArslanArdavic** [bounswe/bounswe2023group9#326]
### Issue Description

GET API request regarding to Proof model will be handled via appropriate back-end implentation.  

### Steps

- [x] End-point regarding to GET API will be specified.
- [x] View related to Proof model will be implemented.
- [x] Implementing and running tests.

### Deadline for the Issue

30.10.2023 - Monday - 23.59

**Comment by hakanaktas0** [comment]
PR has been reviewed and merged.
