### ISSUE TITLE
Enhancement for Home Page

### ISSUE THREAD

**Issue by mehmetSuzer** [bounswe/bounswe2023group9#328]
### Issue Description

Home page needs some enhancements.

### Steps

- [x] Create a smallNode model (title, author, date)
- [x] Enhancements for Home Page Nodes  (colors, elevation, design)
- [x] Search Filters (nodes, users, authors)
- [x] Create a card for users

### Deadline for the Issue

31.10.2023 11.00

**Comment by omerfaunal** [comment]
Reviewed the new design, everything seems smooth and working. Issue can be closed @mehmetSuzer

**Comment by omerfaunal** [comment]
Did some updates on your work in branch home-page-update. Please check and merge to the frontend branch if everything is OK

**Comment by mehmetSuzer** [comment]
I solved the scrolling problem of the home page with Responsive. It would be nice to check it

**Comment by omerfaunal** [comment]
Merged to main
