### ISSUE TITLE
Question about Annotation Requirements - I would like to hear your opinion!

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#33]
### Problem & Question
Some requirements don't seem coherent within themselves to me, and I wonder if I missed something. Should annotations be created by **_Basic Users_**? If so, should we refer to these annotations as **_Private Annotations_**, which can only be seen by their creator, while **_Public Annotations_** are created by contributors and can be seen by anyone?

### Related Requirements
I have realized while reviewing Use Case diagrams. These are the requirements which contradict with each other:
- 1.1.1.2.2 Basic users shall be able to create annotations for a node.
- 1.2.4.1 Annotations shall be added by contributors of the node.

### Suggestion
Since **Basic Users** are not allowed to create node, they can't be contributor of a node. I suggest that we _**should delete Requirement 1.1.1.2.2**_. Other possible solution, separating Annotations as Public and Private.

### Need your opinion - Thank you!
I would appreciate your opinion on this matter. Please share your ideas in the comments, indicating whether you agree or disagree with me. Additionally, please mention which solution you think is the best among possible options.  I will revise the related requirements accordingly to the majority's decision.

**Comment by Bera0422** [comment]
I think that it would be better to allow **_Contributors_** to create **_Public_** or _**Private Annotations**_ while allowing **_Basic Users_** to create only **_Private Annotations_**.

**Comment by hakanaktas0** [comment]
I think we should also limit which contributors can create public annotations to which nodes.

**Comment by laylaylo** [comment]
Thanks for your comments! 

As we discussed this in our previous weekly meeting, we have agreed to allow all registered users to create Private Annotations, while Contributors can additionally create Public Annotations for the Nodes they create. I have updated the requirements as follows:

**old:**
- 1.1.1.1.3 Guests shall be able to view the questions, answers and annotations for each node.
**new:**
- 1.1.1.1.3 Guests shall be able to view the questions, answers and public annotations of each node.

**old:**
- 1.1.1.2.2 Basic users shall be able to create annotations for a node.
**new:**
- 1.1.1.2.2 Basic users shall be able to create private annotations for a node.

**old:**
- 1.1.1.3.4 Contributors shall be able to create annotations for a node.
**new:**
- 1.1.1.3.4 Contributors shall be able to create public annotations for the nodes they create.

**old:** 
- 1.2.4 Annotations
     * 1.2.4.1 Annotations shall be added by contributors of the node.
     *1.2.4.2 Annotations should be sorted by their date.
**new:**
- 1.2.4 Annotations
     * 1.2.4.1 Public annotations should  be visible to anyone.
     * 1.2.4.1 Private annotations should be visible only to their creator.
     *1.2.4.2 Annotations should be sorted by their date.

Could someone review it? @hakanaktas0 @Bera0422

**Comment by hakanaktas0** [comment]
Changes in the requirements adequately correspond to what we discussed.
