### ISSUE TITLE
Enhancement for Profile Page

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#332]
### Issue Description

Profile page needs some enhancements like showing activity of user, merging redundant files, integrating with backend.

### Steps

- [x] integrate Profile GET API with profile page UI
- [x] merge screens/profile_page/profile_page.dart and screens/profile_page/profile_options.dart, since they are doing same thing with different ways and only one is used
- [x] add tab bar below AboutMe section which shows user activity, one tab for published works and other for asked questions
- [x] make published works tab clickable which should open that node view page
- [x] EditProfile and LogOut should be visible only on own profile page
- [x] receive key data to see others profile pages, integrate with search functionality on home page

### Deadline for the Issue

31.10.2023 Tuesday 11.00

**Comment by laylaylo** [comment]
Remaining issues: Questions and Published work part is now dummy text. It needs to be integrated with backend and also navigable to Node View Page. Also ProfilePage should receive a key data to make able to search other profiles, and be navigable from Home Page search functionality.
Other than these, general layout is done. Binding to Profile GET API is also done by @Zulalm. Here are screenshots of both mobile and desktop. Design might be improved based on feedbacks.
**Mobile:**
<img width="495" alt="Screenshot 2023-10-30 at 03 01 35" src="https://github.com/bounswe/bounswe2023group9/assets/74381463/c7068ed5-2a3c-4fd0-ab10-86743dca37a1">
**Desktop:**
<img width="1434" alt="Screenshot 2023-10-30 at 03 00 37" src="https://github.com/bounswe/bounswe2023group9/assets/74381463/b327edb6-8183-4268-b6a1-e7348475c6c9">

**Comment by omerfaunal** [comment]
Solved conflicts in the branchs, did some formatting and reviewed.

**Comment by Zulalm** [comment]
Implemented navigation from home page and node view page to profile page with @laylaylo and @defabdullah  . Now, It is possible to see other user's profile page.  Also, we added onTap functionality to the published works listed in the profile page to navigate to the related node details page.  Questions and answers tab will be updated after the needed API calls are provided.

**Comment by laylaylo** [comment]
this issue is completed by the help of all frontend team, thanks! Screenshots of latest version below,
**mobile:** 
<img width="497" alt="Screenshot 2023-10-31 at 00 37 30" src="https://github.com/bounswe/bounswe2023group9/assets/74381463/5bf1032b-e98b-4047-9e0a-ebea94da3e44">
**desktop:**
<img width="1151" alt="Screenshot 2023-10-31 at 00 57 11" src="https://github.com/bounswe/bounswe2023group9/assets/74381463/5534b657-651e-487f-9de9-e7b0040750a8">
