### ISSUE TITLE
Search Enhancement

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#344]
### Issue Description

In its current state, search doesn't support semantic tags. It should be implemented in the future.

### Steps

- [ ] Implemented
- [ ] Tests implemented
- [ ] PR created 
- [ ] PR merged

**Comment by omerfaunal** [comment]
Left some reviews. Please check them

**Comment by hakanaktas0** [comment]
With the latest PR, the search now supports semantic and random search.
