### ISSUE TITLE
Customer Milestone 1 Report

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#374]
### Issue Description

A report for the Customer Milestone 1 should be prepared.

### Steps

- [x] File Created
- [x] #384
- [x] #385
- [x] #382
- [x] #381
- [x] #379
- [x] #380
- [x] #377
- [x] #386 
- [x] #375
- [x] #383
- [x] #390
- [x] #378 
- [x] #392
- [x] Individual Contribution - Ali Mert Geben 
- [x] Individual Contribution - Oğuz Pançuk
- [x] #389
- [x] #388
- [x] #387 
- [x] #394 
- [x] #391 

### Deadline for the Issue

03.11.2023

**Comment by uyduranomer** [comment]
Everything is done, the report is ready and merged. I am closing this issue
