### ISSUE TITLE
Organize Frontend File Structure

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#405]
**Issue Description**
Frontend file structure should be organized. Each widget should be created in a seperate file. Widgets used in a screen should be located in the widgets folder of the related screen's folder.

**Steps**
- [x] Organize the file structure
- [x] PR

**Deadline**
14.11.2023

**Comment by Zulalm** [comment]
Files of the frontend of the project are rearranged to seperate all the classes into different files. PR is successfully merged.
