### ISSUE TITLE
FE - Enhance Node View Page

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#406]
**Issue Description**

Node view page should be improved based on feedbacks given in the customer presentation. 

**Issue Steps**
- [x] Implement Node Provider
- [x] Improve UI-UX
- [x] Connect provider to screen

**Deadline**
14.11.23

**Comment by Zulalm** [comment]
Node details provider is implemented with the new API call. Provider is connected to the screen. PR is merged to the frontend branch.

**Comment by Zulalm** [comment]
A button is added to link node details page with the related graph page.  Related PR is ready to review. [#456 ](https://github.com/bounswe/bounswe2023group9/pull/456)
Router is also updated while merging the previous PR. 
This issue can be closed after the approval of the [#456 ](https://github.com/bounswe/bounswe2023group9/pull/456)
