### ISSUE TITLE
FE - Node View Details Page UI Bug

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#420]
### Issue Description

There is some pixel overflow in Node View Details Page

<img width="1205" alt="Screenshot 2023-11-13 at 15 31 57" src="https://github.com/bounswe/bounswe2023group9/assets/56688420/de2ccb72-5469-4fb1-a414-9e371dd4947c">

### Steps

- [ ] ...
- [ ] ...
- [ ] ...

**Comment by Zulalm** [comment]
this bug is fixed by #437
