### ISSUE TITLE
FE - Implement Error Handler To Pages

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#425]
### Issue Description

We need to implement user friendly error logic

### Steps

- [x] Graph page
- [x] Home page
- [x] Profile page 
- [x] Node View page
<s>Workspace page</s>

### Deadline for the Issue

21.03.2023

**Comment by laylaylo** [comment]
PR created for all pages except workspace since it's not merged into frontend yet.

**Comment by laylaylo** [comment]
Workspace page doesn't have any API hence no provider connected to the backend yet, so error handling will be done later. Previous PR includes all other pages and merged to frontend, this task is done.
