### ISSUE TITLE
PR reference mix-up in lab_report_05.md

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2023group9#435]
https://github.com/bounswe/bounswe2023group9/blob/79357d666204ac66d9885a1476c3df2bc5d050c2/reports/lab_report_05.md?plain=1#L23

This item (Implement Generic Design) and the item that follows (Revise Login-Signup Flow) have their PR references mixed up.

**Comment by omerfaunal** [comment]
Thanks for the warning. Fixed and merged it.
