### ISSUE TITLE
PR text and PR link mismatch on your Report #6 (for lab #7)

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2023group9#454]
https://github.com/bounswe/bounswe2023group9/blame/620762a510f542253b3a395790e08f13f0f49e2f/reports/lab_report_06.md#L24C205-L24C205

The link to the PR on this line is to the wrong PR. It is linked to #418 instead of #410.

**Comment by Bera0422** [comment]
Fixed the missing link.
