### ISSUE TITLE
Node Class

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#46]
Node Class is to be prepared for the Class Diagram

**Comment by Zulalm** [comment]
Class diagram for the node class was written and needs review. It can also be seen on this [link:](https://lucid.app/lucidchart/68361e85-695a-4c99-b073-3bf5da13b35c/edit?invitationId=inv_f7c380fa-3aed-452b-8bf6-2687b31241ec&page=r.VLewbugIZd#)
![image](https://user-images.githubusercontent.com/111250696/230482048-4e3a54e2-6dd1-4dc9-90b8-230902028e10.png)

**Comment by hakanaktas0** [comment]
This class has been reviewed and ready to be merged to the Class Diagram of the project.
