### ISSUE TITLE
FE - Implement Latex

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#473]
### Issue Description

Implement the TexDocument() widget from _flutter_tex_ on relevant sections of the Node View and Graph pages.

Enhance DB to reflect the significance of this update. Additionally, make general adjustments if time permits.

### Steps

- [x] update Node View page
- [x] update Graph page
- [x] Add meaningful nodes with formulas to DB for showcase of our LaTeX renderer in presentation :)
- [x] DB cleaning - convert all theorems&proofs in nodes to latex format

### Deadline for the Issue

27.11.2023

**Comment by omerfaunal** [comment]
@laylaylo What is the status of this task? Can we finish this by Sunday night?

**Comment by laylaylo** [comment]
@omerfaunal I have not started yet but it won't take long since I did similar implementation while researching its usage. Is it blocking something? I was planning to do it on Monday afternoon, but if there is sth depending on this task, I will try my best for today.

**Comment by laylaylo** [comment]
PR is created for including configuration of _flutter_tex_ and implementation of it on **node view** and **graph** pages.
I also solved problem of seeing titles with strange characters by applying utf8.decode on text data of node with this PR. I changed it anywhere needed but I might overlooked. Now, everything seems kind of in order on search & node view & graph & profile, thanks to we used same node card everywhere :)

I learnt how to access and modify DB today from @Simurgan, thanks again! However, will do DB-related part tomorrow, it shouldn't be blocking dockerization, right?

**Comment by Simurgan** [comment]
> PR is created for including configuration of _flutter_tex_ and implementation of it on **node view** and **graph** pages, added you @omerfaunal as reviewer.
> 
> 
> 
> I also solved problem of seeing titles with strange characters by applying utf8.decode on text data of node with this PR. I changed it anywhere needed but I might overlooked. Now, everything seems kind of in order on search & node view & graph & profile, thanks to we used same node card everywhere :)
> 
> 
> 
> I learnt how to access and modify DB today from @Simurgan, thanks again! However, will do DB-related part tomorrow, it shouldn't be blocking dockerization, right?

You are right @laylaylo , you can do it after dockerization too. Database server is seperated from the backend server. The only problem that might occur for such cases is that backend deploy may modify the database tables and after that change, the data you manipulated before may be lost if for example that column is removed from that table. On the other hand, as far as I know, for our case: backend deployment has already been performed. Plus, we haven't made such a change in the migration. In conclusion, it must be okay to postpone it.

**Comment by laylaylo** [comment]
I cleaned DB from dummy or improper format nodes.

New meaningful nodes along with their contributors and wiki tags are added to be able show what we have done so far for tomorrow's presentation.

To summarize all node data we have accordingly to their tags:

**language theory** and **theory of computation**
- Theorem 1.25 in Language Theory
- Equivalence in Complexity Power: DFA and NFA 
- Myhill - Nerode Theorem
- Finite state verifiers with constant private randomness
- Finite state verifiers with both private and public coins
- Implementing a polynomial-time “clock” in a probabilistic finite automaton

**boolean algebra**
- De Morgan's First Theorem
- De Morgan's Second Theorem
- Duality Principle
- Consensus Theorem
- Huntington's Postulate

**theory of computation**
- Ladner's Theorem

**arithmetic**
- Gödel's First Incompleteness Theorem
- Gödel's Second Incompleteness Theorem

**calculus**
- Fundamental Theorem of Calculus
