### ISSUE TITLE
FE - Configure Please Login Page

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#474]
### Issue Description

Enhance user-friendliness by providing informative content for various pages to highlight the advantages of signing up/in for users who are not yet logged in.

When a guest attempts to access _/workspace_ or _/workspace/x_, include an explanation of what the workspace is, highlight the actions that can be performed; _/profile page_, provide an explanation about information displayed, actions that can be taken; _/notification_  page explain types of notifications users can receive & direct to sign up - sign in.

### Steps

- [x] Workspace specific 
- [x] Profile specific
- [x] Notification specific

### Deadline for the Issue

27.11.2023

**Comment by laylaylo** [comment]
PR is created and it resolves all subtasks in this issue

**Comment by laylaylo** [comment]
PR is merged, hence this task is done.
