### ISSUE TITLE
FE - Connect Provider to Workspace Page

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#477]
### Issue Description

Connect Provider to Workspace Page

### Steps

- [x] Connect provider to Web Workspace.
- [x] Connect provider to Mobile Workspace.

### Deadline for the Issue

28.11.2023

**Comment by Zulalm** [comment]
Web and mobile pages display the data from the backend now. Creating new workspace functionality is also implemented.

**Comment by Zulalm** [comment]
Users are able to create new entries, edit or delete existing entries. Related PR is ready to review.

**Comment by Zulalm** [comment]
Workspace title can be changed and references can be added to workspaces. I will add sending collaboration request feature after merging #588 since the feature needs to be integrated to these changes.

**Comment by Zulalm** [comment]
I couldn't add collaboration request feature since the request id field is missing. This issue will be handled in [#602](https://github.com/bounswe/bounswe2023group9/issues/602)
