### ISSUE TITLE
FE - Web Workspace Page Enhancement

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#478]
### Issue Description

Web workspace page should be improved. Issued discussed so far are listed below. If we encounter more problems we can discuss under this issue.

### Steps

- [x] UI & UX bugs should be inspected and fixed.
- [x] Collaboration request should be shown on contributors section.
- [x] Entry type should not be selectable.
- [x] PR

**Comment by Zulalm** [comment]
Since I forgot that we decided not to include the changing title feature for this milestone, I will delete the "Workspace title should be editable." step.

**Comment by Zulalm** [comment]
Web workspace page's UI &UX is improved. Minor bugs are solved. Related PR is ready to review #521 .

**Comment by Zulalm** [comment]
PR is merged therefore this issue can be closed.
