### ISSUE TITLE
Review Request Class

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#51]
Review Request Class is to be prepared for the Class Diagram

**Comment by oguzpancuk** [comment]
Review Request Class is prepared. I'm not sure about the nodeID. Should we change its name to "node" and type to Node? Needs review.

**Comment by hakanaktas0** [comment]
The issue regarding node part is resolved. An additional class named Review has also been added. This class has been reviewed and ready to be merged to the Class Diagram of the project.
