### ISSUE TITLE
FE - Utf decode bug

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#512]
### Issue Description

@laylaylo There is something wrong with home_page_node_card.dart file.
In home page it's rendered correctly but in graph page there are decoding errors. Can you please check?

### Deadline for the Issue

27.11.2023 20.00

**Comment by omerfaunal** [comment]
@laylaylo There is something wrong with home_page_node_card.dart file.
In home page it's rendered correctly but in graph page there are decoding errors. Can you please check?

**Comment by laylaylo** [comment]
@omerfaunal will take a look in 2hour

**Comment by laylaylo** [comment]
This bug was minor and solved with one line code while creating _**'you may like'**_ feature, in PR #522
