### ISSUE TITLE
BE - Profile get info api bug

### ISSUE THREAD

**Issue by defabdullah** [bounswe/bounswe2023group9#515]
### Issue Description

http://13.51.55.11:8000/api/get_profile_info/?mail=abdullah@susuz.com. This api returns 500 error code.

### Steps

- [ ] ...
- [ ] ...
- [ ] ...

### Deadline for the Issue

30.11.2023 - Thursday - 17.00

**Comment by hakanaktas0** [comment]
Bug is fixed and PR is merged
