### ISSUE TITLE
Search Class

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#52]
Search Class is to be prepared for the Class Diagram

**Comment by laylaylo** [comment]
Search class diagram has been created and requires review.
It can also be examined from [this link](https://lucid.app/lucidchart/68361e85-695a-4c99-b073-3bf5da13b35c/edit?viewport_loc=-16%2C-74%2C1877%2C1031%2CsyeMEIAiJflV&invitationId=inv_f7c380fa-3aed-452b-8bf6-2687b31241ec).
<img width="254" alt="Screen Shot 2023-04-07 at 20 58 31" src="https://user-images.githubusercontent.com/74381463/230655497-56133c0d-f9bf-47d1-97d7-6818e09e6603.png">

**Comment by laylaylo** [comment]
As reviewed this in meeting #8, we have concluded that the Search Class has been completed and is ready to be merged into the class diagram for the project.
