### ISSUE TITLE
Semantic Tag Class

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#53]
Semantic Tag Class is to be prepared for the Class Diagram

**Comment by gebenalimert** [comment]
Semantic Tag class diagram has been created and requires review. It can also be examined from this [link.](https://lucid.app/lucidchart/68361e85-695a-4c99-b073-3bf5da13b35c/edit?invitationId=inv_f7c380fa-3aed-452b-8bf6-2687b31241ec&page=hPhMwNiKw20E#)
![tag](https://user-images.githubusercontent.com/79109830/230645529-81dbe3b5-bb09-48bc-9649-cd2c05cf99a9.png)

**Comment by hakanaktas0** [comment]
This class is reviewed and ready to be merged to the Class Diagram of the project.
