### ISSUE TITLE
Annotation Class

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#54]
Annotation Class is to be prepared for the Class Diagram

**Comment by gebenalimert** [comment]
Annotation class diagram has been created and requires review. It can also be examined from this [link.](https://lucid.app/lucidchart/68361e85-695a-4c99-b073-3bf5da13b35c/edit?invitationId=inv_f7c380fa-3aed-452b-8bf6-2687b31241ec&page=s.VLRWo6riYP#)
![annotation](https://user-images.githubusercontent.com/79109830/230645784-d7882f6b-c14e-496d-abb8-166a4a5e1d4c.png)

**Comment by hakanaktas0** [comment]
Class is reviewed and ready to be merged to the Class Diagram of the project.
