### ISSUE TITLE
Notification Class

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#55]
Notification Class is to be prepared for the Class Diagram

**Comment by laylaylo** [comment]
Notification class diagram has been created and requires review. 
It can also be examined from [this link](https://lucid.app/lucidchart/68361e85-695a-4c99-b073-3bf5da13b35c/edit?viewport_loc=94%2C57%2C1458%2C800%2C0_0&invitationId=inv_f7c380fa-3aed-452b-8bf6-2687b31241ec).
<img width="280" alt="Screen Shot 2023-04-07 at 20 53 26" src="https://user-images.githubusercontent.com/74381463/230654986-016c6ecd-d37e-49e9-88d2-ea7acebe301e.png">

**Comment by laylaylo** [comment]
As reviewed this in meeting8, we have concluded that the Notification Class has been completed and is ready to be merged into the class diagram for the project.
