### ISSUE TITLE
API Documentation Wiki Page 

### ISSUE THREAD

**Issue by ArslanArdavic** [bounswe/bounswe2023group9#556]
### Issue Description

Wiki Page including API Documentation should be created.

### Steps

- [x] Creating a new wiki page
- [x] Adding pdf of API Documentation to wiki pae

### Deadline for the Issue

01.12.2023 - 17.00

**Comment by ArslanArdavic** [comment]
Done without hesitation.

**Comment by Brunettow** [comment]
It looks nice, well done.
