### ISSUE TITLE
Link to the wrong issue in lab_report_07.md

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2023group9#562]
https://github.com/bounswe/bounswe2023group9/blob/6e0ec546c4fc57ec6f9ca6042d297dc6903fe81a/reports/lab_report_07.md?plain=1#L59

The line above links to a different issue than that is written in text. This is a recurring issue, please be more careful about it in your later reports.

**Comment by omerfaunal** [comment]
#563 done, thanks and sorry
