### ISSUE TITLE
FE - Workspace Add New Features

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#566]
### Issue Description

Workspace Add New Features

### Steps

- [x] Add semantic tags
- [x] Add request message to collaboration request.
- [ ] ~Specify collaborator for every entry.~
- [x] ~Latex for entries~
- [x] Editable text instead of a pop up while editing entries.

### Deadline for the Issue

12.12.2023

**Comment by mehmetSuzer** [comment]
I opened a PR for step 2, 4, and 5.

**Comment by laylaylo** [comment]
**Note:** Since LaTeX solution that is going to be implemented for enabling annotations is not certain yet, using latex for entries in workspace is subject to change according to it.

**Comment by Zulalm** [comment]
As we discussed on the lab, we do not need to specify collaborators of the entries on the workspace.

**Comment by mehmetSuzer** [comment]
Semantic tags are added, too.
