### ISSUE TITLE
FE - Question/Answer Implementation

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#567]
### Issue Description

Question/Answer Implementation

### Steps

- [x] Q/A page design on Node Details Page
- [x] Implement Activity on Profile Page
- [x] Provider for posting a question
- [x] Provider for answering a question
- [x] Change functionality according to user type (owner, user, guest)

#### Deadline: 12.12.23 - 15.00

**Comment by Brunettow** [comment]
I reviewed the code. The implementations works without a problem. However there can be little adjustments in terms of button designs.
