### ISSUE TITLE
Creating Sequence Diagram for the Project

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#58]
### Issue Description

Sequence Diagram for the project should be prepared. 

### Reminders
- Sequence diagram shows _interactions_ between _objects_ with **lifelines**
- Each sequence shows **object interaction** for **one use case**.
- Objects being used in sequence should have a class in our prepared class diagrams.
- Use case being used in sequence should exist in our prepared use case diagrams.
- Objects are arranged in a time sequence.

### Steps

- [x] #59
- [x] #60
- [x] #61
- [x] #62
- [x] #63 

### Deadline for the Issue

 08.04.2023 - Saturday - 21.00

**Comment by uyduranomer** [comment]
All of the squence diagrams are in this zip file: 
[Sequence Diagrams.zip](https://github.com/bounswe/bounswe2023group9/files/11191254/Sequence.Diagrams.zip)

They all needs review...
