### ISSUE TITLE
Sequence Diagrams for Guest Interactions

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#59]
Sequence Diagrams of Use Cases for Guest Interactions should be prepared.
Required Use Cases:
- [x] Review sequence diagrams
- [x] View questions about node
- [x] View annotations about node
- [x] View profile pages
- [x] Provide unregistered e-mail
- [x] Provide a safe password
- [x] Provide real name and surname
- [x] Accept privacy policies
- [x] Verify the provided e-mail address
- [x] Sign Up

**Comment by hakanaktas0** [comment]
I reviewed the sequence diagrams for this user and all sequence diagrams are consistent with the requirements and what we discussed with the PO.
