### ISSUE TITLE
FE - Add Review Feature to Workspace Page

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#596]
### Issue Description
Contributors should be able to send their workspaces to review. Reviewers should be able to comment on the workspaces. Reviewers should be able to accept or reject workspaces. Workspaces should be turned into nodes after approval.

### Steps

- [x] Workspaces page should be edited to support send review feature.
- [x] Workspaces page should support review feature.

### Deadline for the Issue

25.12.2023

**Comment by Zulalm** [comment]
Contributors are able to finalize and send their workspaces to review. Reviewers can see the workspaces that they can review. Add review function is also implemented. However, add review button is visible to all users. It should be visible only to reviewers of the workspace. Workspaces page will be updated according to user roles.

**Comment by Zulalm** [comment]
Workspaces page is updated according to user roles. Review request can be accepted or rejected now. Related PR [#676 ](https://github.com/bounswe/bounswe2023group9/pull/676)

**Comment by Zulalm** [comment]
Since the PR is merged this issue can be closed.
