### ISSUE TITLE
FE - Admin Features

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#597]
### Issue Description

Admin Features

### Steps
Hide Node Feature
- [x] Hide/Show button to node details page
- [x] Make available the button only for Admin
- [x] Throw 404 Page not found error for hidden node except admin
- [x] Get user type from backend
- [x] Connect to the backend

Ban-Unban Feature
- [x] Ban/unban button to profile page
- [x] Make available the button only for Admin
- [x] Throw 404 Page not found error for hidden node except admin
- [x] Get user type from backend
- [x] Connect to backend

Hide Q/A Feature
- [x] Hide/show button to questions/answers
- [x] Make available the button only for Admin
- [x] On pressed the questions won't be visible except admin
- [x] Get user type from backend
- [x] Connect to backend

Choose as a Reviewer Feature
- [x] Choose as a reviewer button to profile page
- [x] Make available the button only for Admin
- [x] Get user type from backend
- [x] Connect to backend

Final Check
- [x] Bug Fix

### Deadline for the Issue

19.12.23  ~  15.00

### Updated Deadline
25.12.23 ~ 22.00

**Comment by Brunettow** [comment]
I wrote dummy question id to admin provider. This is just a reminder to me. It will be updated after I pull from frontend branch.(Question answer branch is just merged to the frontend branch)

**Comment by Brunettow** [comment]
All the tasks (except question/answer admin features) are completed. Here are the button designs:
![DeepinScreenshot_select-area_20231220013323](https://github.com/bounswe/bounswe2023group9/assets/63921045/28daf5e7-ba3e-4424-8d3f-5f1c6381a13f)

**Comment by Brunettow** [comment]
### Hide Nodes button:

![DeepinScreenshot_select-area_20231220013632](https://github.com/bounswe/bounswe2023group9/assets/63921045/8b768b79-c2ee-4d18-8bfa-489afe4e6092)
