### ISSUE TITLE
FE - Privacy Policy to Login Page

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#598]
### Issue Description

Add a show privacy policy button with dummy text to login/signup page

### Steps

- [x] Add clickable Text
- [x] Implement pop-up privacy page
- [x] Add a checkbox and update button activation 
- [x] Add a dummy privacy policy text 
- [x] Fix overflow errors

### Deadline for the Issue

19.12.23  ~ 15.00

**Comment by Brunettow** [comment]
Implementation is completed. 

Since privacy policy hasn't been implemented yet, we used a dummy text for now. 

Pop-up page design may be enhanced however It is good enough for now and I recommend to may be change it after adding the real privacy policy text to get best results.

**Comment by Brunettow** [comment]
Privacy policy is completed and merged to the frontend branch.
