### ISSUE TITLE
Sequence Diagrams for Basic User Interactions

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#60]
Sequence Diagrams of Use Cases for Basic User Interactions should be prepared.
Required Use Cases:

- [x] Ask question about a node
- [x] Create annotation for a node
- [x] Edit annotation
- [x] Delete annotation
- [x] View annotation
- [x] View own profile page
- [x] Log in
- [x] Log out
- [x] Get notifications

**Comment by Bera0422** [comment]
Added required use cases to the issue description.

**Comment by Bera0422** [comment]
Sequence diagrams for the following use cases is completed and added to [this link](https://lucid.app/lucidchart/b4879e49-fad8-4c20-a5a8-8b6811bf29a5/edit?page=936MRjw9K-Qd#)
-  Ask question about a node
- Create annotation for a node
- View own profile page
- Log out
- Get notifications

**Comment by laylaylo** [comment]
Sequence diagrams for the following use cases is completed and added to [this link](https://lucid.app/lucidchart/b4879e49-fad8-4c20-a5a8-8b6811bf29a5/edit?page=936MRjw9K-Qd#)

- Log in
- View annotation made by oneself
- View annotation made by contributor 
- Edit annotation text
- Delete annotation text

<img width="310" alt="Screen Shot 2023-04-10 at 12 24 18" src="https://user-images.githubusercontent.com/74381463/230874137-3d167c1c-de64-45f4-b5d1-78ced02087f2.png">

**Comment by laylaylo** [comment]
We discussed and reviewed UML sequence diagrams with @Bera0422  on Discord. The diagrams appeared both logically and syntactically correct, and covered all use cases of the Basic User as described in our UML use case diagrams. Additionally, they were coherent with our UML class diagrams. As all steps related to this issue have been completed, I will now be closing it.
