### ISSUE TITLE
Sequence Diagrams for Contributor Interactions

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#61]
Sequence Diagrams of Use Cases for Contributor Interactions should be prepared.

Steps:

- [x] View Workspace
- [x] Create Workspace
- [x] Create Entry
- [x] Edit Entry
- [x] Answer Question
- [x] Delete Question
- [x] Send collaboration request
- [x] Answer collaboration request

**Comment by hakanaktas0** [comment]
I reviewed the sequence diagrams for this user and all sequence diagrams are consistent with the requirements and what we discussed with the PO.
