### ISSUE TITLE
Sequence Diagrams for Admin Interactions

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#63]
Sequence Diagrams of Use Cases for Admin Interactions should be prepared.

- [x] Ban User Sequence 
- [x] Unban User Sequence
- [x] Remove Node Sequence
- [x] Remove Proof Sequence
- [x] Remove Question Sequence

**Comment by mehmetSuzer** [comment]
Sequence diagrams for admin has been completed

**Comment by hakanaktas0** [comment]
I reviewed the sequence diagrams for this user and all sequence diagrams are consistent with the requirements and what we discussed with the PO.
