### ISSUE TITLE
Individual Contribution Reports

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#64]
### Issue Description

Each group member must prepare Wiki page about the individual contribution report.

### Steps

- [x] #65 
- [x] #66 
- [x] #67 
- [x] #68
- [x] #69 
- [x] #70 
- [x] #71 
- [x] #72 
- [x] #73 
- [x] #74

### Deadline for the Issue

10.04.2023

**Comment by uyduranomer** [comment]
All of the individual contributon reports have been created and added to the milestone 1 report
