### ISSUE TITLE
FE - Add semantic tags (Workspace and User Profile)

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#648]
### Issue Description

User add semantic tags

### Steps

- [x] Implement a search bar for semantic tags
- [x] Add semantic tag  in workspace
- [x] Remove semantic tag from a workspace
- [x] Add semantic tags to profile page
- [ ] Remove semantic tags from a profile page

26.12.2023

**Comment by mehmetSuzer** [comment]
Users can add tags for their profiles. In addition, they can add tags to their unfinalized workspaces. 
They can remove added tags from their profiles and unfinalized workspaces.
PR #698 and #723
