### ISSUE TITLE
FE - Real Privacy Text

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#650]
### Issue Description

Content of privacy text should be real

### Steps

- [x] Change dummy privacy text with the real one
- [x] Adjust the content design if needed

### Deadline for the Issue

26.12.23

**Comment by Brunettow** [comment]
I added the real text to the proivacy policy page, adjusted the design accordingly.
Current view of the page: 

<img src='https://github.com/bounswe/bounswe2023group9/assets/63921045/1e9500d9-d7ee-410b-82e4-4ade3d55f103' width='500'>
