### ISSUE TITLE
FE - ORCID Frontend

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#651]
### Issue Description

In our project, users registers the platform as a basic user. To become a contributor. User should provide a unique ORC ID. For that, a mechanism is needed to be added to frontend.

### Steps

- [x] Write ORCID input widget
- [x] Write provider
- [x] Connect to the backend

### Deadline for the Issue

25.12.23 ~ 23.59

**Comment by Brunettow** [comment]
I talked with frontend team and we decided to put this mechanism to the settings page.

**Comment by Brunettow** [comment]
New settings page view:

<img src='https://github.com/bounswe/bounswe2023group9/assets/63921045/c60a6c9f-32e5-4e20-bf72-dc283b6558f8' width='600'>
