### ISSUE TITLE
FE - Test of Everything

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#652]
### Issue Description

Good luck!

### Steps

- [x] **Functionality Verification:** Ensure that the existing features align with the project requirements. Identify any discrepancies or missing elements.
- [x] **Scenario-Based Testing:** Conduct tests that mimic real-world usage to assess the required functionalities. Aim for a seamless user experience.
- [x] **Bug Hunt:** Vigilantly search for any issues, be they in logic or in the user interface design.
- [x] **Collaboration Alert:** Reach out to the respective task owners for necessary revisions or updates :) I will be the annoying one for final days of our project...

### Deadline for the Issue

25.12.2023

**Comment by laylaylo** [comment]
Noticed that the questions in a node aren't sorted. To align with our requirement _1.2.3.1 "Questions shall be sorted either by date or by popularity"_, can we implement sorting by date? @defabdullah

**Comment by laylaylo** [comment]
I've noticed the 'Edit Profile' pop-up is experiencing bottom overflow issues, and it appears the functionality isn't fully implemented yet. I'm aware @Brunettow is on the case (thanks for that!), but I just want to confirm: once these updates are completed, will they cover all our requirements for Profile Preferences? 

**_1.1.4 Profile Preferences_**
- _1.1.4.1 Basic users shall be able to change their passwords._
- _1.1.4.3 Basic users shall be able to let their profile pages show their activity._
- _1.1.4.5 Basic users shall be able to edit their own profile information._
- _1.1.4.6 Basic users shall be able to turn on or off the email notifications._

**Comment by Brunettow** [comment]
Let me check the overflow error, thank you for pointing out that.
Yes, all these requirements are satisfied.

**Comment by laylaylo** [comment]
As we released our app, this issue is no longer valid.
