### ISSUE TITLE
Milestone Scenario

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#653]
### Issue Description

A scenario for final milestone demo will be prepared to demonstrate all functionality implemented since milestone 2 well. Also, mock data will be prepared for this purpose and will be applied to the database.

### Steps

- [x] Scenario preparation
- [x] Mock data preparation
- [x] Mock data insertion to DB

### Deadline for the Issue

26.12.2023

**Comment by Simurgan** [comment]
We have prepared the scenario and performed the demo. Also we have inserted the mock data to the DB. It was shown in the demo presentation too. I am closing this issue.
