### ISSUE TITLE
FE - Settings Bug Fix

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#656]
### Issue Description

Settings Bug Fix

### Steps

We detected a bug in settings page. We will make sure it works properly. Also we will check overflow errors and fix them.

### Deadline for the Issue

25.12.23 ~ 22.00

**Comment by Brunettow** [comment]
There were several problems in settings page and the provider wasn't working.
I detected that the problem stem from several issues related with updates in project. I fixed them and they are now works well.
