### ISSUE TITLE
Writing Privacy Policy

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#663]
### Issue Description

A privacy policy should be written about the platform and added to relevant page.

- [x] Research on writing privacy policy
- [x] Writing the draft of the privacy policy
- [x] Finalize the privacy policy text

_No response_

### Deadline for the Issue

28.12.2023 ~ 15.00

**Comment by Brunettow** [comment]
Abdullah wrote the Privacy policy and we reviewed together. Finalized version can be found [here](https://github.com/bounswe/bounswe2023group9/wiki/Privacy-Policy).
