### ISSUE TITLE
Individual Contribution Report for Leyla Yayladere

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#70]
### Issue Description

Individual Contribution Report must be prepared for Leyla Yayladere

### Deadline for the Issue

10.04.2023

**Comment by laylaylo** [comment]
I prepared my individual contribution report and created a[ wiki page ](https://github.com/bounswe/bounswe2023group9/wiki/Individual-Contribution-Report-by-Leyla-Yayladere) for it.
