### ISSUE TITLE
Reviewers should not see the contributors of a Review Request

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#705]
### Issue Description

Reviewers should not see the contributors of a Review Request. Contributors section of the workspace should be unvisible to reviewers.

### Steps

- [x] Modify workspace page to hide contributors to reviewers.

### Deadline for the Issue

25.12.2023

**Comment by Zulalm** [comment]
I modified the workspace page to make contributors section to reviewers. Related PR is ready to be reviewed.
