### ISSUE TITLE
Individual Contribution Report for Ömer Şükrü Uyduran

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#73]
### Issue Description

Individual Contribution Report must be prepared for Ömer Şükrü Uyduran

### Deadline for the Issue

10.04.2023

**Comment by uyduranomer** [comment]
I created my [individual contribution report](https://github.com/bounswe/bounswe2023group9/wiki/Individual-Contribution-Report-by-Ömer-Şükrü-Uyduran)
