### ISSUE TITLE
Executive Summary

### ISSUE THREAD

**Issue by mehmetSuzer** [bounswe/bounswe2023group9#733]
### Issue Description

Write the executive summary of the final milestone stone report.

### Deadline for the Issue

29.12.2023 17:00

**Comment by mehmetSuzer** [comment]
The executive summary related to guests, basic users, and contributors are added to the final milestone report. 

Reviewers and the admin parts are left. I think those who worked on the implementation of these user types should fill the rest.

**Comment by Zulalm** [comment]
I made some additions to the contributors section and wrote the reviewers section.

**Comment by mehmetSuzer** [comment]
A small paragraph for the admin is added to the report. So, the executive summary is completed.
