### ISSUE TITLE
Individial Reports

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2023group9#735]
### Issue Description

Each team member will report their individual contributions.

 - [x] Individual Contribution - Ali Mert Geben 
 - [x] #736
 - [x] #738 
 - [x] #739
 - [x] Individual Contibution - Bengisu Kübra Takkin
 - [x] Individual Contibution - Hakan Emre Aktaş
 - [x] Individual Contibution - Arda Arslan
 - [x] Individual Contibution - Zülal Molla
 - [x] Individual Contibution - Leyla Yayladere
 - [x] #743
 - [x] Individual Contibution - Ahmed Bera Pay 
 Individual Contibution - Oğuz Pançuk?

### Deadline for the Issue

29.12.23 23.59

**Comment by laylaylo** [comment]
Added my contributions to the wiki page of report.
