### ISSUE TITLE
Individual Contribution Report for Zülal Molla

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#74]
### Issue Description

Individual Contribution Report must be prepared for Zülal Molla

### Deadline for the Issue

10.04.2023

**Comment by Zulalm** [comment]
Created a page named Individual Contribution Report - Zülal Molla. Listed all tasks I was responsible for. Listed my main contributions and gave relavant issue and wiki page links. And added it to the wiki sidebar. It can be found under the individual contribution reports section. [see here](https://github.com/bounswe/bounswe2023group9/wiki/Individual-Contribution-Report---Z%C3%BClal-Molla)
