### ISSUE TITLE
Milestone Report

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#77]
### Issue Description

Milestone Report should be prepared, 

### Steps

- [x] Introduction
- [x] Table of Contents
- [x] #81
- [x] #82
- [x] #83
- [x] #84
- [x] #64 
- [x] #89 

Also Deliverables;
- [x] Project repository
- [x] #88 
- [x] #87 
- [x] #75 
- [x] #76 
- [x] #79 
- [x] #78 

### Deadline for the Issue

10.04.2023 23.59

**Comment by uyduranomer** [comment]
The report has been completed and I reviewed it. It looks really great. Good job everyone, we have completed the milestone 1.
