### ISSUE TITLE
All Team Members Should Fill the Responsibility Assignment Matrix

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#79]
### Issue Description

All members should fill the RAM.

### Steps

- [x] Hakan Emre Aktas
- [x] Ahmet Bera Pay
- [x] Omer Sukru Uyduran
- [x] Mehmet Suzer
- [x] Ahmet Abdullah Susuz
- [x] Ali Mert Geben
- [x] Oguz Pancuk
- [x] Arda Arslan
- [x] Zulal Molla
- [x] Leyla Yayladere

### Deadline for the Issue

10.04.2023

**Comment by laylaylo** [comment]
I filled my column in the excel

**Comment by hakanaktas0** [comment]
All team members have filled the RAM and it is added to the milestone report 1 in wiki,
