### ISSUE TITLE
Executive Summary

### ISSUE THREAD

**Issue by Zulalm** [bounswe/bounswe2023group9#81]
**Issue Description**
 Summary of project status and any changes in plans based on reflections should be documented.

**Steps**
- [x] Project Description
- [x] Project Status

**Deadline for the Issue**
10.04.2023

**Comment by Zulalm** [comment]
Executive summary are added to related Google Docs. It needs to be reviewed and added to Wiki page of the Milestone#1.

**Comment by hakanaktas0** [comment]
I have reviewed this section and it is added to the milestone report 1 in wiki.
