### ISSUE TITLE
List and status of deliverables.

### ISSUE THREAD

**Issue by Zulalm** [bounswe/bounswe2023group9#82]
**Issue Description**
List and status of deliverables should be documented.

**Deadline for the Issue**
10.04.2023

**Comment by Zulalm** [comment]
List and status of deliverables are documented on related Google Docs. It needs to be reviewed and added to Wiki page of the Milestone#1.

**Comment by hakanaktas0** [comment]
It has been reviewed and added to the milestone report page of the wiki.
