### ISSUE TITLE
Use Case Diagrams will be combined

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#85]
### Issue Description

Use case diagrams which are prepared by different people and stored in different pages at the moment will be combined in a single page.

### Deadline for the Issue

10.04.2023

**Comment by uyduranomer** [comment]
They are combined with generalization and edited cosmeticly. Also view node and view profile pages actions added to the basic user. It can be found in the combined diagrams page of the lucidchart workspace. Also it is attached as pdf here:
[Use Case Diagram - Combined Diagram.pdf](https://github.com/bounswe/bounswe2023group9/files/11190875/Use.Case.Diagram.-.Combined.Diagram.pdf)

**Comment by laylaylo** [comment]
Here is the updated version of it as pdf.
[Use Case Diagram - Combined Diagram.pdf](https://github.com/bounswe/bounswe2023group9/files/11191192/Use.Case.Diagram.-.Combined.Diagram.pdf)

**Comment by uyduranomer** [comment]
Hi @laylaylo . Thanks for the review. Also thanks for the little nice editings :)
