### ISSUE TITLE
Software design documents in UML will be added to milestone report

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#87]
### Issue Description

Software design documents in UML will be added to its specified part in the milestone report (7.3)

### Steps

- [x] #91 
- [x] #90 
- [x] #92 
- [x] Created pages will be referenced in the Milestone 1 report

### Deadline for the Issue

10.04.2023

**Comment by uyduranomer** [comment]
The pages were created and referenced in the [relevant part (7.1) of the Milestone 1 report](https://github.com/bounswe/bounswe2023group9/wiki/Milestone-1-Report#73-software-design-documents-in-uml).

This isse needs review...

**Comment by hakanaktas0** [comment]
I have reviewed the sections added by @uyduranomer and the hyperlinks added to the milestone report correspond to the right pages in wiki.
