### ISSUE TITLE
Requirements will be added to milestone report

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#88]
### Issue Description

Requirements will be added to its specified part in the milestone report (7.2)

### Steps

- [x] [requirements page](https://github.com/bounswe/bounswe2023group9/wiki/Requirements) will be added to 7.2.1
- [x] [scenarios and mock-ups](https://github.com/bounswe/bounswe2023group9/wiki#-scenarios-and-mock-ups) will be added to 7.2.2

### Deadline for the Issue

10.04.2023

**Comment by uyduranomer** [comment]
they are added to the [7.2 Requirements part](https://github.com/bounswe/bounswe2023group9/wiki/Milestone-1-report#72---requirements) in [Milestone 1 report](https://github.com/bounswe/bounswe2023group9/wiki/Milestone-1-report)

This issue needs review currently

**Comment by hakanaktas0** [comment]
I reviewed the corresponding part of the milestone report and the links in the milestone report correspond to requirements page of the repository.
