### ISSUE TITLE
Milestone Report will be transferred to wiki

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#89]
### Issue Description

Milestone Report will be transferred to wiki by using wiki markdown. The page has to be placed under the milestone reports tab in the wiki sidebar too. The name of the page must be 'Milestone 1 report'.

### Steps

- [x] #92 
- [x] #91 
- [x] #90 
- [x] Milestone report will be transferred
- [x] The page will be added to the sidebar under Milestone Deliverables tab

### Deadline for the Issue

10.04.2023

**Comment by mehmetSuzer** [comment]
Milestone report that we have written in Google Docs so far has been transfered to a wiki page. 
Side has been edited.
Please review it.

**Comment by hakanaktas0** [comment]
I have reviewed this issue and all sections we created in the Google Docs are transferred to the Milestone report correctly. With the addition of Diagrams by @uyduranomer this issue is completed and can be closed.
