### ISSUE TITLE
Class Diagram Page will be created

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#90]
### Issue Description

Class Diagram Page will be created and placed in the wiki sidebar to refer in the Milestone 1 report.

### Steps

- [x] Class Diagram Page will be created
- [x] The created page will be added to the wiki sidebar

### Deadline for the Issue

10.04.2023

**Comment by uyduranomer** [comment]
[Class Diagram page](https://github.com/bounswe/bounswe2023group9/wiki/Class-Diagram) has been created and added to the wiki sidebar

This issue needs review.

**Comment by hakanaktas0** [comment]
I have reviewed the diagrams added to the wiki and they are as we discussed in the meetings.
