### ISSUE TITLE
Use Case Diagram Page will be created

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#91]
### Issue Description

Use Case Diagram Page will be created and placed in the wiki sidebar to refer in the Milestone 1 report.

### Steps

- [x] Use case diagram Page will be created
- [x] The created page will be added to the wiki sidebar

### Deadline for the Issue

10.04.2023

**Comment by uyduranomer** [comment]
[Use Case Diagram page](https://github.com/bounswe/bounswe2023group9/wiki/Use-Case-Diagram) has been created and added to the wiki sidebar

This issue needs review.

**Comment by hakanaktas0** [comment]
I have reviewed the diagrams added to the wiki and they are as we discussed in the meetings.
