### ISSUE TITLE
Third Party API Research

### ISSUE THREAD

**Issue by hakanaktas0** [bounswe/bounswe2023group9#94]
### Issue Description

Every team member should find a third party API to research and utilize.

### Steps

- [x] #97 
- [x] #106 
- [x] DOAJ API - #96
- [x] Semantic Scholar API - #95
- [x] #102
- [x] #99
- [x] #103 
- [x] #104
- [x] Oğuz Pançuk -#105
- [x] #98
- [x] #161 

### Deadline for the Issue

As soon as possible

**Comment by defabdullah** [comment]
I will work on Semantic Scholar API. I created subissue.

**Comment by mehmetSuzer** [comment]
DOAJ is a unique and extensive index of diverse open access journals from around the world.
I will utilise DOAJ API.

**Comment by Bera0422** [comment]
I will use ERIC  API. [ERIC](https://eric.ed.gov/?) (Education Resources Information Center) offers a comprehensive online bibliographic and full-text database of education research and information.

**Comment by hakanaktas0** [comment]
I will utilize SerpApi. It is an API for Google Search that also supports Google Scholar. I decided to use it because Google Scholar doesn't have an API of its own.

**Comment by Zulalm** [comment]
I will use ORCID API to implement registration functionality of our application.  I chose it since it is a public API that allows us to register users without any fee with reasonable limitations.

**Comment by gebenalimert** [comment]
I will utilize Zenodo API which is an API enabling researchers from all disciplines to share and preserve their research outputs.

**Comment by laylaylo** [comment]
I opted for the [Elsevier ScienceDirect API](https://www.elsevier.com/solutions/sciencedirect/librarian-resource-center/api) for article retrieval to quickly search for articles within ScienceDirect using a RESTful interface. This API provides several response formats and detailed documentation, simplifying the integration process. Although  obtaining a token for free is easy, the usage of the API is limited without a ScienceDirect subscription.

**Comment by uyduranomer** [comment]
I will utilize the [CORE API](https://core.ac.uk/services/api) which supplies access to the largest collection of open papers on the world.

**Comment by laylaylo** [comment]
Since I encountered issues while working with my previous API, I opted to switch to another one. I have decided to utilize [the NASA STI Repository OpenAPI](https://www.sti.nasa.gov/docs/20221122_OpenAPI_Documentation.pdf).

**Comment by uyduranomer** [comment]
All of the subissues have been completed.
